<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('countries')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('countries')->insert([
            ['code' => 'AF', 'title_en' => 'Afghanistan', 'title_ar' => 'أفغانستان', 'nationality_en' => 'Afghan', 'nationality_ar' => 'أفغانستاني'],
            ['code' => 'AL', 'title_en' => 'Albania', 'title_ar' => 'ألبانيا', 'nationality_en' => 'Albanian', 'nationality_ar' => 'ألباني'],
            ['code' => 'AX', 'title_en' => 'Aland Islands', 'title_ar' => 'جزر آلاند', 'nationality_en' => 'Aland Islander', 'nationality_ar' => 'آلاندي'],
            ['code' => 'DZ', 'title_en' => 'Algeria', 'title_ar' => 'الجزائر', 'nationality_en' => 'Algerian', 'nationality_ar' => 'جزائري'],
            ['code' => 'AS', 'title_en' => 'American Samoa', 'title_ar' => 'ساموا-الأمريكي', 'nationality_en' => 'American Samoan', 'nationality_ar' => 'أمريكي سامواني'],
            ['code' => 'AD', 'title_en' => 'Andorra', 'title_ar' => 'أندورا', 'nationality_en' => 'Andorran', 'nationality_ar' => 'أندوري'],
            ['code' => 'AO', 'title_en' => 'Angola', 'title_ar' => 'أنغولا', 'nationality_en' => 'Angolan', 'nationality_ar' => 'أنقولي'],
            ['code' => 'AI', 'title_en' => 'Anguilla', 'title_ar' => 'أنغويلا', 'nationality_en' => 'Anguillan', 'nationality_ar' => 'أنغويلي'],
            ['code' => 'AQ', 'title_en' => 'Antarctica', 'title_ar' => 'أنتاركتيكا', 'nationality_en' => 'Antarctican', 'nationality_ar' => 'أنتاركتيكي'],
            ['code' => 'AG', 'title_en' => 'Antigua and Barbuda', 'title_ar' => 'أنتيغوا وبربودا', 'nationality_en' => 'Antiguan', 'nationality_ar' => 'بربودي'],
            ['code' => 'AR', 'title_en' => 'Argentina', 'title_ar' => 'الأرجنتين', 'nationality_en' => 'Argentinian', 'nationality_ar' => 'أرجنتيني'],
            ['code' => 'AM', 'title_en' => 'Armenia', 'title_ar' => 'أرمينيا', 'nationality_en' => 'Armenian', 'nationality_ar' => 'أرميني'],
            ['code' => 'AW', 'title_en' => 'Aruba', 'title_ar' => 'أروبه', 'nationality_en' => 'Aruban', 'nationality_ar' => 'أوروبهيني'],
            ['code' => 'AU', 'title_en' => 'Australia', 'title_ar' => 'أستراليا', 'nationality_en' => 'Australian', 'nationality_ar' => 'أسترالي'],
            ['code' => 'AT', 'title_en' => 'Austria', 'title_ar' => 'النمسا', 'nationality_en' => 'Austrian', 'nationality_ar' => 'نمساوي'],
            ['code' => 'AZ', 'title_en' => 'Azerbaijan', 'title_ar' => 'أذربيجان', 'nationality_en' => 'Azerbaijani', 'nationality_ar' => 'أذربيجاني'],
            ['code' => 'BS', 'title_en' => 'Bahamas', 'title_ar' => 'الباهاماس', 'nationality_en' => 'Bahamian', 'nationality_ar' => 'باهاميسي'],
            ['code' => 'BH', 'title_en' => 'Bahrain', 'title_ar' => 'البحرين', 'nationality_en' => 'Bahraini', 'nationality_ar' => 'بحريني'],
            ['code' => 'BD', 'title_en' => 'Bangladesh', 'title_ar' => 'بنغلاديش', 'nationality_en' => 'Bangladeshi', 'nationality_ar' => 'بنغلاديشي'],
            ['code' => 'BB', 'title_en' => 'Barbados', 'title_ar' => 'بربادوس', 'nationality_en' => 'Barbadian', 'nationality_ar' => 'بربادوسي'],
            ['code' => 'BY', 'title_en' => 'Belarus', 'title_ar' => 'روسيا البيضاء', 'nationality_en' => 'Belarusian', 'nationality_ar' => 'روسي'],
            ['code' => 'BE', 'title_en' => 'Belgium', 'title_ar' => 'بلجيكا', 'nationality_en' => 'Belgian', 'nationality_ar' => 'بلجيكي'],
            ['code' => 'BZ', 'title_en' => 'Belize', 'title_ar' => 'بيليز', 'nationality_en' => 'Belizean', 'nationality_ar' => 'بيليزي'],
            ['code' => 'BJ', 'title_en' => 'Benin', 'title_ar' => 'بنين', 'nationality_en' => 'Beninese', 'nationality_ar' => 'بنيني'],
            ['code' => 'BL', 'title_en' => 'Saint Barthelemy', 'title_ar' => 'سان بارتيلمي', 'nationality_en' => 'Saint Barthelmian', 'nationality_ar' => 'سان بارتيلمي'],
            ['code' => 'BM', 'title_en' => 'Bermuda', 'title_ar' => 'جزر برمودا', 'nationality_en' => 'Bermudan', 'nationality_ar' => 'برمودي'],
            ['code' => 'BT', 'title_en' => 'Bhutan', 'title_ar' => 'بوتان', 'nationality_en' => 'Bhutanese', 'nationality_ar' => 'بوتاني'],
            ['code' => 'BO', 'title_en' => 'Bolivia', 'title_ar' => 'بوليفيا', 'nationality_en' => 'Bolivian', 'nationality_ar' => 'بوليفي'],
            ['code' => 'BA', 'title_en' => 'Bosnia and Herzegovina', 'title_ar' => 'البوسنة و الهرسك', 'nationality_en' => 'Bosnian / Herzegovinian', 'nationality_ar' => 'بوسني/هرسكي'],
            ['code' => 'BW', 'title_en' => 'Botswana', 'title_ar' => 'بوتسوانا', 'nationality_en' => 'Botswanan', 'nationality_ar' => 'بوتسواني'],
            ['code' => 'BV', 'title_en' => 'Bouvet Island', 'title_ar' => 'جزيرة بوفيه', 'nationality_en' => 'Bouvetian', 'nationality_ar' => 'بوفيهي'],
            ['code' => 'BR', 'title_en' => 'Brazil', 'title_ar' => 'البرازيل', 'nationality_en' => 'Brazilian', 'nationality_ar' => 'برازيلي'],
            ['code' => 'IO', 'title_en' => 'British Indian Ocean Territory', 'title_ar' => 'إقليم المحيط الهندي البريطاني', 'nationality_en' => 'British Indian Ocean Territory', 'nationality_ar' => 'إقليم المحيط الهندي البريطاني'],
            ['code' => 'BN', 'title_en' => 'Brunei Darussalam', 'title_ar' => 'بروني', 'nationality_en' => 'Bruneian', 'nationality_ar' => 'بروني'],
            ['code' => 'BG', 'title_en' => 'Bulgaria', 'title_ar' => 'بلغاريا', 'nationality_en' => 'Bulgarian', 'nationality_ar' => 'بلغاري'],
            ['code' => 'BF', 'title_en' => 'Burkina Faso', 'title_ar' => 'بوركينا فاسو', 'nationality_en' => 'Burkinabe', 'nationality_ar' => 'بوركيني'],
            ['code' => 'BI', 'title_en' => 'Burundi', 'title_ar' => 'بوروندي', 'nationality_en' => 'Burundian', 'nationality_ar' => 'بورونيدي'],
            ['code' => 'KH', 'title_en' => 'Cambodia', 'title_ar' => 'كمبوديا', 'nationality_en' => 'Cambodian', 'nationality_ar' => 'كمبودي'],
            ['code' => 'CM', 'title_en' => 'Cameroon', 'title_ar' => 'كاميرون', 'nationality_en' => 'Cameroonian', 'nationality_ar' => 'كاميروني'],
            ['code' => 'CA', 'title_en' => 'Canada', 'title_ar' => 'كندا', 'nationality_en' => 'Canadian', 'nationality_ar' => 'كندي'],
            ['code' => 'CV', 'title_en' => 'Cape Verde', 'title_ar' => 'الرأس الأخضر', 'nationality_en' => 'Cape Verdean', 'nationality_ar' => 'الرأس الأخضر'],
            ['code' => 'KY', 'title_en' => 'Cayman Islands', 'title_ar' => 'جزر كايمان', 'nationality_en' => 'Caymanian', 'nationality_ar' => 'كايماني'],
            ['code' => 'CF', 'title_en' => 'Central African Republic', 'title_ar' => 'جمهورية أفريقيا الوسطى', 'nationality_en' => 'Central African', 'nationality_ar' => 'أفريقي'],
            ['code' => 'TD', 'title_en' => 'Chad', 'title_ar' => 'تشاد', 'nationality_en' => 'Chadian', 'nationality_ar' => 'تشادي'],
            ['code' => 'CL', 'title_en' => 'Chile', 'title_ar' => 'شيلي', 'nationality_en' => 'Chilean', 'nationality_ar' => 'شيلي'],
            ['code' => 'CN', 'title_en' => 'China', 'title_ar' => 'الصين', 'nationality_en' => 'Chinese', 'nationality_ar' => 'صيني'],
            ['code' => 'CX', 'title_en' => 'Christmas Island', 'title_ar' => 'جزيرة عيد الميلاد', 'nationality_en' => 'Christmas Islander', 'nationality_ar' => 'جزيرة عيد الميلاد'],
            ['code' => 'CC', 'title_en' => 'Cocos (Keeling) Islands', 'title_ar' => 'جزر كوكوس', 'nationality_en' => 'Cocos Islander', 'nationality_ar' => 'جزر كوكوس'],
            ['code' => 'CO', 'title_en' => 'Colombia', 'title_ar' => 'كولومبيا', 'nationality_en' => 'Colombian', 'nationality_ar' => 'كولومبي'],
            ['code' => 'KM', 'title_en' => 'Comoros', 'title_ar' => 'جزر القمر', 'nationality_en' => 'Comorian', 'nationality_ar' => 'جزر القمر'],
            ['code' => 'CG', 'title_en' => 'Congo', 'title_ar' => 'الكونغو', 'nationality_en' => 'Congolese', 'nationality_ar' => 'كونغي'],
            ['code' => 'CK', 'title_en' => 'Cook Islands', 'title_ar' => 'جزر كوك', 'nationality_en' => 'Cook Islander', 'nationality_ar' => 'جزر كوك'],
            ['code' => 'CR', 'title_en' => 'Costa Rica', 'title_ar' => 'كوستاريكا', 'nationality_en' => 'Costa Rican', 'nationality_ar' => 'كوستاريكي'],
            ['code' => 'HR', 'title_en' => 'Croatia', 'title_ar' => 'كرواتيا', 'nationality_en' => 'Croatian', 'nationality_ar' => 'كوراتي'],
            ['code' => 'CU', 'title_en' => 'Cuba', 'title_ar' => 'كوبا', 'nationality_en' => 'Cuban', 'nationality_ar' => 'كوبي'],
            ['code' => 'CY', 'title_en' => 'Cyprus', 'title_ar' => 'قبرص', 'nationality_en' => 'Cypriot', 'nationality_ar' => 'قبرصي'],
            ['code' => 'CW', 'title_en' => 'Curaçao', 'title_ar' => 'كوراساو', 'nationality_en' => 'Curacian', 'nationality_ar' => 'كوراساوي'],
            ['code' => 'CZ', 'title_en' => 'Czech Republic', 'title_ar' => 'الجمهورية التشيكية', 'nationality_en' => 'Czech', 'nationality_ar' => 'تشيكي'],
            ['code' => 'DK', 'title_en' => 'Denmark', 'title_ar' => 'الدانمارك', 'nationality_en' => 'Danish', 'nationality_ar' => 'دنماركي'],
            ['code' => 'DJ', 'title_en' => 'Djibouti', 'title_ar' => 'جيبوتي', 'nationality_en' => 'Djiboutian', 'nationality_ar' => 'جيبوتي'],
            ['code' => 'DM', 'title_en' => 'Dominica', 'title_ar' => 'دومينيكا', 'nationality_en' => 'Dominican', 'nationality_ar' => 'دومينيكي'],
            ['code' => 'DO', 'title_en' => 'Dominican Republic', 'title_ar' => 'الجمهورية الدومينيكية', 'nationality_en' => 'Dominican', 'nationality_ar' => 'دومينيكي'],
            ['code' => 'EC', 'title_en' => 'Ecuador', 'title_ar' => 'إكوادور', 'nationality_en' => 'Ecuadorian', 'nationality_ar' => 'إكوادوري'],
            ['code' => 'EG', 'title_en' => 'Egypt', 'title_ar' => 'مصر', 'nationality_en' => 'Egyptian', 'nationality_ar' => 'مصري'],
            ['code' => 'SV', 'title_en' => 'El Salvador', 'title_ar' => 'إلسلفادور', 'nationality_en' => 'Salvadoran', 'nationality_ar' => 'سلفادوري'],
            ['code' => 'GQ', 'title_en' => 'Equatorial Guinea', 'title_ar' => 'غينيا الاستوائي', 'nationality_en' => 'Equatorial Guinean', 'nationality_ar' => 'غيني'],
            ['code' => 'ER', 'title_en' => 'Eritrea', 'title_ar' => 'إريتريا', 'nationality_en' => 'Eritrean', 'nationality_ar' => 'إريتيري'],
            ['code' => 'EE', 'title_en' => 'Estonia', 'title_ar' => 'استونيا', 'nationality_en' => 'Estonian', 'nationality_ar' => 'استوني'],
            ['code' => 'ET', 'title_en' => 'Ethiopia', 'title_ar' => 'أثيوبيا', 'nationality_en' => 'Ethiopian', 'nationality_ar' => 'أثيوبي'],
            ['code' => 'FK', 'title_en' => 'Falkland Islands (Malvinas)', 'title_ar' => 'جزر فوكلاند', 'nationality_en' => 'Falkland Islander', 'nationality_ar' => 'فوكلاندي'],
            ['code' => 'FO', 'title_en' => 'Faroe Islands', 'title_ar' => 'جزر فارو', 'nationality_en' => 'Faroese', 'nationality_ar' => 'جزر فارو'],
            ['code' => 'FJ', 'title_en' => 'Fiji', 'title_ar' => 'فيجي', 'nationality_en' => 'Fijian', 'nationality_ar' => 'فيجي'],
            ['code' => 'FI', 'title_en' => 'Finland', 'title_ar' => 'فنلندا', 'nationality_en' => 'Finnish', 'nationality_ar' => 'فنلندي'],
            ['code' => 'FR', 'title_en' => 'France', 'title_ar' => 'فرنسا', 'nationality_en' => 'French', 'nationality_ar' => 'فرنسي'],
            ['code' => 'GF', 'title_en' => 'French Guiana', 'title_ar' => 'غويانا الفرنسية', 'nationality_en' => 'French Guianese', 'nationality_ar' => 'غويانا الفرنسية'],
            ['code' => 'PF', 'title_en' => 'French Polynesia', 'title_ar' => 'بولينيزيا الفرنسية', 'nationality_en' => 'French Polynesian', 'nationality_ar' => 'بولينيزيي'],
            ['code' => 'TF', 'title_en' => 'French Southern and Antarctic Lands', 'title_ar' => 'أراض فرنسية جنوبية وأنتارتيكية', 'nationality_en' => 'French', 'nationality_ar' => 'أراض فرنسية جنوبية وأنتارتيكية'],
            ['code' => 'GA', 'title_en' => 'Gabon', 'title_ar' => 'الغابون', 'nationality_en' => 'Gabonese', 'nationality_ar' => 'غابوني'],
            ['code' => 'GM', 'title_en' => 'Gambia', 'title_ar' => 'غامبيا', 'nationality_en' => 'Gambian', 'nationality_ar' => 'غامبي'],
            ['code' => 'GE', 'title_en' => 'Georgia', 'title_ar' => 'جيورجيا', 'nationality_en' => 'Georgian', 'nationality_ar' => 'جيورجي'],
            ['code' => 'DE', 'title_en' => 'Germany', 'title_ar' => 'ألمانيا', 'nationality_en' => 'German', 'nationality_ar' => 'ألماني'],
            ['code' => 'GH', 'title_en' => 'Ghana', 'title_ar' => 'غانا', 'nationality_en' => 'Ghanaian', 'nationality_ar' => 'غاني'],
            ['code' => 'GI', 'title_en' => 'Gibraltar', 'title_ar' => 'جبل طارق', 'nationality_en' => 'Gibraltar', 'nationality_ar' => 'جبل طارق'],
            ['code' => 'GG', 'title_en' => 'Guernsey', 'title_ar' => 'غيرنزي', 'nationality_en' => 'Guernsian', 'nationality_ar' => 'غيرنزي'],
            ['code' => 'GR', 'title_en' => 'Greece', 'title_ar' => 'اليونان', 'nationality_en' => 'Greek', 'nationality_ar' => 'يوناني'],
            ['code' => 'GL', 'title_en' => 'Greenland', 'title_ar' => 'جرينلاند', 'nationality_en' => 'Greenlandic', 'nationality_ar' => 'جرينلاندي'],
            ['code' => 'GD', 'title_en' => 'Grenada', 'title_ar' => 'غرينادا', 'nationality_en' => 'Grenadian', 'nationality_ar' => 'غرينادي'],
            ['code' => 'GP', 'title_en' => 'Guadeloupe', 'title_ar' => 'جزر جوادلوب', 'nationality_en' => 'Guadeloupe', 'nationality_ar' => 'جزر جوادلوب'],
            ['code' => 'GU', 'title_en' => 'Guam', 'title_ar' => 'جوام', 'nationality_en' => 'Guamanian', 'nationality_ar' => 'جوامي'],
            ['code' => 'GT', 'title_en' => 'Guatemala', 'title_ar' => 'غواتيمال', 'nationality_en' => 'Guatemalan', 'nationality_ar' => 'غواتيمالي'],
            ['code' => 'GN', 'title_en' => 'Guinea', 'title_ar' => 'غينيا', 'nationality_en' => 'Guinean', 'nationality_ar' => 'غيني'],
            ['code' => 'GW', 'title_en' => 'Guinea-Bissau', 'title_ar' => 'غينيا-بيساو', 'nationality_en' => 'Guinea-Bissauan', 'nationality_ar' => 'غيني'],
            ['code' => 'GY', 'title_en' => 'Guyana', 'title_ar' => 'غيانا', 'nationality_en' => 'Guyanese', 'nationality_ar' => 'غياني'],
            ['code' => 'HT', 'title_en' => 'Haiti', 'title_ar' => 'هايتي', 'nationality_en' => 'Haitian', 'nationality_ar' => 'هايتي'],
            ['code' => 'HM', 'title_en' => 'Heard and Mc Donald Islands', 'title_ar' => 'جزيرة هيرد وجزر ماكدونالد', 'nationality_en' => 'Heard and Mc Donald Islanders', 'nationality_ar' => 'جزيرة هيرد] وجزر ماكدونالد'],
            ['code' => 'HN', 'title_en' => 'Honduras', 'title_ar' => 'هندوراس', 'nationality_en' => 'Honduran', 'nationality_ar' => 'هندوراسي'],
            ['code' => 'HK', 'title_en' => 'Hong Kong', 'title_ar' => 'هونغ كونغ', 'nationality_en' => 'Hongkongese', 'nationality_ar' => 'هونغ كونغي'],
            ['code' => 'HU', 'title_en' => 'Hungary', 'title_ar' => 'المجر', 'nationality_en' => 'Hungarian', 'nationality_ar' => 'مجري'],
            ['code' => 'IS', 'title_en' => 'Iceland', 'title_ar' => 'آيسلندا', 'nationality_en' => 'Icelandic', 'nationality_ar' => 'آيسلندي'],
            ['code' => 'IN', 'title_en' => 'India', 'title_ar' => 'الهند', 'nationality_en' => 'Indian', 'nationality_ar' => 'هندي'],
            ['code' => 'IM', 'title_en' => 'Isle of Man', 'title_ar' => 'جزيرة مان', 'nationality_en' => 'Manx', 'nationality_ar' => 'ماني'],
            ['code' => 'ID', 'title_en' => 'Indonesia', 'title_ar' => 'أندونيسيا', 'nationality_en' => 'Indonesian', 'nationality_ar' => 'أندونيسيي'],
            ['code' => 'IR', 'title_en' => 'Iran', 'title_ar' => 'إيران', 'nationality_en' => 'Iranian', 'nationality_ar' => 'إيراني'],
            ['code' => 'IQ', 'title_en' => 'Iraq', 'title_ar' => 'العراق', 'nationality_en' => 'Iraqi', 'nationality_ar' => 'عراقي'],
            ['code' => 'IE', 'title_en' => 'Ireland', 'title_ar' => 'إيرلندا', 'nationality_en' => 'Irish', 'nationality_ar' => 'إيرلندي'],
            ['code' => 'IL', 'title_en' => 'Israel', 'title_ar' => 'إسرائيل', 'nationality_en' => 'Israeli', 'nationality_ar' => 'إسرائيلي'],
            ['code' => 'IT', 'title_en' => 'Italy', 'title_ar' => 'إيطاليا', 'nationality_en' => 'Italian', 'nationality_ar' => 'إيطالي'],
            ['code' => 'CI', 'title_en' => 'Ivory Coast', 'title_ar' => 'ساحل العاج', 'nationality_en' => 'Ivory Coastian', 'nationality_ar' => 'ساحل العاج'],
            ['code' => 'JE', 'title_en' => 'Jersey', 'title_ar' => 'جيرزي', 'nationality_en' => 'Jersian', 'nationality_ar' => 'جيرزي'],
            ['code' => 'JM', 'title_en' => 'Jamaica', 'title_ar' => 'جمايكا', 'nationality_en' => 'Jamaican', 'nationality_ar' => 'جمايكي'],
            ['code' => 'JP', 'title_en' => 'Japan', 'title_ar' => 'اليابان', 'nationality_en' => 'Japanese', 'nationality_ar' => 'ياباني'],
            ['code' => 'JO', 'title_en' => 'Jordan', 'title_ar' => 'الأردن', 'nationality_en' => 'Jordanian', 'nationality_ar' => 'أردني'],
            ['code' => 'KZ', 'title_en' => 'Kazakhstan', 'title_ar' => 'كازاخستان', 'nationality_en' => 'Kazakh', 'nationality_ar' => 'كازاخستاني'],
            ['code' => 'KE', 'title_en' => 'Kenya', 'title_ar' => 'كينيا', 'nationality_en' => 'Kenyan', 'nationality_ar' => 'كيني'],
            ['code' => 'KI', 'title_en' => 'Kiribati', 'title_ar' => 'كيريباتي', 'nationality_en' => 'I-Kiribati', 'nationality_ar' => 'كيريباتي'],
            ['code' => 'KP', 'title_en' => 'Korea(North Korea)', 'title_ar' => 'كوريا الشمالية', 'nationality_en' => 'North Korean', 'nationality_ar' => 'كوري'],
            ['code' => 'KR', 'title_en' => 'Korea(South Korea)', 'title_ar' => 'كوريا الجنوبية', 'nationality_en' => 'South Korean', 'nationality_ar' => 'كوري'],
            ['code' => 'XK', 'title_en' => 'Kosovo', 'title_ar' => 'كوسوفو', 'nationality_en' => 'Kosovar', 'nationality_ar' => 'كوسيفي'],
            ['code' => 'KW', 'title_en' => 'Kuwait', 'title_ar' => 'الكويت', 'nationality_en' => 'Kuwaiti', 'nationality_ar' => 'كويتي'],
            ['code' => 'KG', 'title_en' => 'Kyrgyzstan', 'title_ar' => 'قيرغيزستان', 'nationality_en' => 'Kyrgyzstani', 'nationality_ar' => 'قيرغيزستاني'],
            ['code' => 'LA', 'title_en' => 'Lao PDR', 'title_ar' => 'لاوس', 'nationality_en' => 'Laotian', 'nationality_ar' => 'لاوسي'],
            ['code' => 'LV', 'title_en' => 'Latvia', 'title_ar' => 'لاتفيا', 'nationality_en' => 'Latvian', 'nationality_ar' => 'لاتيفي'],
            ['code' => 'LB', 'title_en' => 'Lebanon', 'title_ar' => 'لبنان', 'nationality_en' => 'Lebanese', 'nationality_ar' => 'لبناني'],
            ['code' => 'LS', 'title_en' => 'Lesotho', 'title_ar' => 'ليسوتو', 'nationality_en' => 'Basotho', 'nationality_ar' => 'ليوسيتي'],
            ['code' => 'LR', 'title_en' => 'Liberia', 'title_ar' => 'ليبيريا', 'nationality_en' => 'Liberian', 'nationality_ar' => 'ليبيري'],
            ['code' => 'LY', 'title_en' => 'Libya', 'title_ar' => 'ليبيا', 'nationality_en' => 'Libyan', 'nationality_ar' => 'ليبي'],
            ['code' => 'LI', 'title_en' => 'Liechtenstein', 'title_ar' => 'ليختنشتين', 'nationality_en' => 'Liechtenstein', 'nationality_ar' => 'ليختنشتيني'],
            ['code' => 'LT', 'title_en' => 'Lithuania', 'title_ar' => 'لتوانيا', 'nationality_en' => 'Lithuanian', 'nationality_ar' => 'لتوانيي'],
            ['code' => 'LU', 'title_en' => 'Luxembourg', 'title_ar' => 'لوكسمبورغ', 'nationality_en' => 'Luxembourger', 'nationality_ar' => 'لوكسمبورغي'],
            ['code' => 'LK', 'title_en' => 'Sri Lanka', 'title_ar' => 'سريلانكا', 'nationality_en' => 'Sri Lankian', 'nationality_ar' => 'سريلانكي'],
            ['code' => 'MO', 'title_en' => 'Macau', 'title_ar' => 'ماكاو', 'nationality_en' => 'Macanese', 'nationality_ar' => 'ماكاوي'],
            ['code' => 'MK', 'title_en' => 'Macedonia', 'title_ar' => 'مقدونيا', 'nationality_en' => 'Macedonian', 'nationality_ar' => 'مقدوني'],
            ['code' => 'MG', 'title_en' => 'Madagascar', 'title_ar' => 'مدغشقر', 'nationality_en' => 'Malagasy', 'nationality_ar' => 'مدغشقري'],
            ['code' => 'MW', 'title_en' => 'Malawi', 'title_ar' => 'مالاوي', 'nationality_en' => 'Malawian', 'nationality_ar' => 'مالاوي'],
            ['code' => 'MY', 'title_en' => 'Malaysia', 'title_ar' => 'ماليزيا', 'nationality_en' => 'Malaysian', 'nationality_ar' => 'ماليزي'],
            ['code' => 'MV', 'title_en' => 'Maldives', 'title_ar' => 'المالديف', 'nationality_en' => 'Maldivian', 'nationality_ar' => 'مالديفي'],
            ['code' => 'ML', 'title_en' => 'Mali', 'title_ar' => 'مالي', 'nationality_en' => 'Malian', 'nationality_ar' => 'مالي'],
            ['code' => 'MT', 'title_en' => 'Malta', 'title_ar' => 'مالطا', 'nationality_en' => 'Maltese', 'nationality_ar' => 'مالطي'],
            ['code' => 'MH', 'title_en' => 'Marshall Islands', 'title_ar' => 'جزر مارشال', 'nationality_en' => 'Marshallese', 'nationality_ar' => 'مارشالي'],
            ['code' => 'MQ', 'title_en' => 'Martinique', 'title_ar' => 'مارتينيك', 'nationality_en' => 'Martiniquais', 'nationality_ar' => 'مارتينيكي'],
            ['code' => 'MR', 'title_en' => 'Mauritania', 'title_ar' => 'موريتانيا', 'nationality_en' => 'Mauritanian', 'nationality_ar' => 'موريتانيي'],
            ['code' => 'MU', 'title_en' => 'Mauritius', 'title_ar' => 'موريشيوس', 'nationality_en' => 'Mauritian', 'nationality_ar' => 'موريشيوسي'],
            ['code' => 'YT', 'title_en' => 'Mayotte', 'title_ar' => 'مايوت', 'nationality_en' => 'Mahoran', 'nationality_ar' => 'مايوتي'],
            ['code' => 'MX', 'title_en' => 'Mexico', 'title_ar' => 'المكسيك', 'nationality_en' => 'Mexican', 'nationality_ar' => 'مكسيكي'],
            ['code' => 'FM', 'title_en' => 'Micronesia', 'title_ar' => 'مايكرونيزيا', 'nationality_en' => 'Micronesian', 'nationality_ar' => 'مايكرونيزيي'],
            ['code' => 'MD', 'title_en' => 'Moldova', 'title_ar' => 'مولدافيا', 'nationality_en' => 'Moldovan', 'nationality_ar' => 'مولديفي'],
            ['code' => 'MC', 'title_en' => 'Monaco', 'title_ar' => 'موناكو', 'nationality_en' => 'Monacan', 'nationality_ar' => 'مونيكي'],
            ['code' => 'MN', 'title_en' => 'Mongolia', 'title_ar' => 'منغوليا', 'nationality_en' => 'Mongolian', 'nationality_ar' => 'منغولي'],
            ['code' => 'ME', 'title_en' => 'Montenegro', 'title_ar' => 'الجبل الأسود', 'nationality_en' => 'Montenegrin', 'nationality_ar' => 'الجبل الأسود'],
            ['code' => 'MS', 'title_en' => 'Montserrat', 'title_ar' => 'مونتسيرات', 'nationality_en' => 'Montserratian', 'nationality_ar' => 'مونتسيراتي'],
            ['code' => 'MA', 'title_en' => 'Morocco', 'title_ar' => 'المغرب', 'nationality_en' => 'Moroccan', 'nationality_ar' => 'مغربي'],
            ['code' => 'MZ', 'title_en' => 'Mozambique', 'title_ar' => 'موزمبيق', 'nationality_en' => 'Mozambican', 'nationality_ar' => 'موزمبيقي'],
            ['code' => 'MM', 'title_en' => 'Myanmar', 'title_ar' => 'ميانمار', 'nationality_en' => 'Myanmarian', 'nationality_ar' => 'ميانماري'],
            ['code' => 'NA', 'title_en' => 'Namibia', 'title_ar' => 'ناميبيا', 'nationality_en' => 'Namibian', 'nationality_ar' => 'ناميبي'],
            ['code' => 'NR', 'title_en' => 'Nauru', 'title_ar' => 'نورو', 'nationality_en' => 'Nauruan', 'nationality_ar' => 'نوري'],
            ['code' => 'NP', 'title_en' => 'Nepal', 'title_ar' => 'نيبال', 'nationality_en' => 'Nepalese', 'nationality_ar' => 'نيبالي'],
            ['code' => 'NL', 'title_en' => 'Netherlands', 'title_ar' => 'هولندا', 'nationality_en' => 'Dutch', 'nationality_ar' => 'هولندي'],
            ['code' => 'AN', 'title_en' => 'Netherlands Antilles', 'title_ar' => 'جزر الأنتيل الهولندي', 'nationality_en' => 'Dutch Antilier', 'nationality_ar' => 'هولندي'],
            ['code' => 'NC', 'title_en' => 'New Caledonia', 'title_ar' => 'كاليدونيا الجديدة', 'nationality_en' => 'New Caledonian', 'nationality_ar' => 'كاليدوني'],
            ['code' => 'NZ', 'title_en' => 'New Zealand', 'title_ar' => 'نيوزيلندا', 'nationality_en' => 'New Zealander', 'nationality_ar' => 'نيوزيلندي'],
            ['code' => 'NI', 'title_en' => 'Nicaragua', 'title_ar' => 'نيكاراجوا', 'nationality_en' => 'Nicaraguan', 'nationality_ar' => 'نيكاراجوي'],
            ['code' => 'NE', 'title_en' => 'Niger', 'title_ar' => 'النيجر', 'nationality_en' => 'Nigerien', 'nationality_ar' => 'نيجيري'],
            ['code' => 'NG', 'title_en' => 'Nigeria', 'title_ar' => 'نيجيريا', 'nationality_en' => 'Nigerian', 'nationality_ar' => 'نيجيري'],
            ['code' => 'NU', 'title_en' => 'Niue', 'title_ar' => 'ني', 'nationality_en' => 'Niuean', 'nationality_ar' => 'ني'],
            ['code' => 'NF', 'title_en' => 'Norfolk Island', 'title_ar' => 'جزيرة نورفولك', 'nationality_en' => 'Norfolk Islander', 'nationality_ar' => 'نورفوليكي'],
            ['code' => 'MP', 'title_en' => 'Northern Mariana Islands', 'title_ar' => 'جزر ماريانا الشمالية', 'nationality_en' => 'Northern Marianan', 'nationality_ar' => 'ماريني'],
            ['code' => 'NO', 'title_en' => 'Norway', 'title_ar' => 'النرويج', 'nationality_en' => 'Norwegian', 'nationality_ar' => 'نرويجي'],
            ['code' => 'OM', 'title_en' => 'Oman', 'title_ar' => 'عمان', 'nationality_en' => 'Omani', 'nationality_ar' => 'عماني'],
            ['code' => 'PK', 'title_en' => 'Pakistan', 'title_ar' => 'باكستان', 'nationality_en' => 'Pakistani', 'nationality_ar' => 'باكستاني'],
            ['code' => 'PW', 'title_en' => 'Palau', 'title_ar' => 'بالاو', 'nationality_en' => 'Palauan', 'nationality_ar' => 'بالاوي'],
            ['code' => 'PS', 'title_en' => 'Palestine', 'title_ar' => 'فلسطين', 'nationality_en' => 'Palestinian', 'nationality_ar' => 'فلسطيني'],
            ['code' => 'PA', 'title_en' => 'Panama', 'title_ar' => 'بنما', 'nationality_en' => 'Panamanian', 'nationality_ar' => 'بنمي'],
            ['code' => 'PG', 'title_en' => 'Papua New Guinea', 'title_ar' => 'بابوا غينيا الجديدة', 'nationality_en' => 'Papua New Guinean', 'nationality_ar' => 'بابوي'],
            ['code' => 'PY', 'title_en' => 'Paraguay', 'title_ar' => 'باراغواي', 'nationality_en' => 'Paraguayan', 'nationality_ar' => 'بارغاوي'],
            ['code' => 'PE', 'title_en' => 'Peru', 'title_ar' => 'بيرو', 'nationality_en' => 'Peruvian', 'nationality_ar' => 'بيري'],
            ['code' => 'PH', 'title_en' => 'Philippines', 'title_ar' => 'الفليبين', 'nationality_en' => 'Filipino', 'nationality_ar' => 'فلبيني'],
            ['code' => 'PN', 'title_en' => 'Pitcairn', 'title_ar' => 'بيتكيرن', 'nationality_en' => 'Pitcairn Islander', 'nationality_ar' => 'بيتكيرني'],
            ['code' => 'PL', 'title_en' => 'Poland', 'title_ar' => 'بولونيا', 'nationality_en' => 'Polish', 'nationality_ar' => 'بوليني'],
            ['code' => 'PT', 'title_en' => 'Portugal', 'title_ar' => 'البرتغال', 'nationality_en' => 'Portuguese', 'nationality_ar' => 'برتغالي'],
            ['code' => 'PR', 'title_en' => 'Puerto Rico', 'title_ar' => 'بورتو ريكو', 'nationality_en' => 'Puerto Rican', 'nationality_ar' => 'بورتي'],
            ['code' => 'QA', 'title_en' => 'Qatar', 'title_ar' => 'قطر', 'nationality_en' => 'Qatari', 'nationality_ar' => 'قطري'],
            ['code' => 'RE', 'title_en' => 'Reunion Island', 'title_ar' => 'ريونيون', 'nationality_en' => 'Reunionese', 'nationality_ar' => 'ريونيوني'],
            ['code' => 'RO', 'title_en' => 'Romania', 'title_ar' => 'رومانيا', 'nationality_en' => 'Romanian', 'nationality_ar' => 'روماني'],
            ['code' => 'RU', 'title_en' => 'Russian', 'title_ar' => 'روسيا', 'nationality_en' => 'Russian', 'nationality_ar' => 'روسي'],
            ['code' => 'RW', 'title_en' => 'Rwanda', 'title_ar' => 'رواندا', 'nationality_en' => 'Rwandan', 'nationality_ar' => 'رواندا'],
            ['code' => 'KN', 'title_en' => 'Saint Kitts and Nevis', 'title_ar' => 'سانت كيتس ونيفس,', 'nationality_en' => 'Kittitian/Nevisian', 'nationality_ar' => 'سانت كيتس ونيفس'],
            ['code' => 'MF', 'title_en' => 'Saint Martin (French part)', 'title_ar' => 'ساينت مارتن فرنسي', 'nationality_en' => 'St. Martian(French)', 'nationality_ar' => 'ساينت مارتني فرنسي'],
            ['code' => 'SX', 'title_en' => 'Sint Maarten (Dutch part)', 'title_ar' => 'ساينت مارتن هولندي', 'nationality_en' => 'St. Martian(Dutch)', 'nationality_ar' => 'ساينت مارتني هولندي'],
            ['code' => 'LC', 'title_en' => 'Saint Pierre and Miquelon', 'title_ar' => 'سان بيير وميكلون', 'nationality_en' => 'St. Pierre and Miquelon', 'nationality_ar' => 'سان بيير وميكلوني'],
            ['code' => 'VC', 'title_en' => 'Saint Vincent and the Grenadines', 'title_ar' => 'سانت فنسنت وجزر غرينادين', 'nationality_en' => 'Saint Vincent and the Grenadines', 'nationality_ar' => 'سانت فنسنت وجزر غرينادين'],
            ['code' => 'WS', 'title_en' => 'Samoa', 'title_ar' => 'ساموا', 'nationality_en' => 'Samoan', 'nationality_ar' => 'ساموي'],
            ['code' => 'SM', 'title_en' => 'San Marino', 'title_ar' => 'سان مارينو', 'nationality_en' => 'Sammarinese', 'nationality_ar' => 'ماريني'],
            ['code' => 'ST', 'title_en' => 'Sao Tome and Principe', 'title_ar' => 'ساو تومي وبرينسيبي', 'nationality_en' => 'Sao Tomean', 'nationality_ar' => 'ساو تومي وبرينسيبي'],
            ['code' => 'SA', 'title_en' => 'Saudi Arabia', 'title_ar' => 'المملكة العربية السعودية', 'nationality_en' => 'Saudi Arabian', 'nationality_ar' => 'سعودي'],
            ['code' => 'SN', 'title_en' => 'Senegal', 'title_ar' => 'السنغال', 'nationality_en' => 'Senegalese', 'nationality_ar' => 'سنغالي'],
            ['code' => 'RS', 'title_en' => 'Serbia', 'title_ar' => 'صربيا', 'nationality_en' => 'Serbian', 'nationality_ar' => 'صربي'],
            ['code' => 'SC', 'title_en' => 'Seychelles', 'title_ar' => 'سيشيل', 'nationality_en' => 'Seychellois', 'nationality_ar' => 'سيشيلي'],
            ['code' => 'SL', 'title_en' => 'Sierra Leone', 'title_ar' => 'سيراليون', 'nationality_en' => 'Sierra Leonean', 'nationality_ar' => 'سيراليوني'],
            ['code' => 'SG', 'title_en' => 'Singapore', 'title_ar' => 'سنغافورة', 'nationality_en' => 'Singaporean', 'nationality_ar' => 'سنغافوري'],
            ['code' => 'SK', 'title_en' => 'Slovakia', 'title_ar' => 'سلوفاكيا', 'nationality_en' => 'Slovak', 'nationality_ar' => 'سولفاكي'],
            ['code' => 'SI', 'title_en' => 'Slovenia', 'title_ar' => 'سلوفينيا', 'nationality_en' => 'Slovenian', 'nationality_ar' => 'سولفيني'],
            ['code' => 'SB', 'title_en' => 'Solomon Islands', 'title_ar' => 'جزر سليمان', 'nationality_en' => 'Solomon Island', 'nationality_ar' => 'جزر سليمان'],
            ['code' => 'SO', 'title_en' => 'Somalia', 'title_ar' => 'الصومال', 'nationality_en' => 'Somali', 'nationality_ar' => 'صومالي'],
            ['code' => 'ZA', 'title_en' => 'South Africa', 'title_ar' => 'جنوب أفريقيا', 'nationality_en' => 'South African', 'nationality_ar' => 'أفريقي'],
            ['code' => 'GS', 'title_en' => 'South Georgia and the South Sandwich', 'title_ar' => 'المنطقة القطبية الجنوبية', 'nationality_en' => 'South Georgia and the South Sandwich', 'nationality_ar' => 'لمنطقة القطبية الجنوبية'],
            ['code' => 'SS', 'title_en' => 'South Sudan', 'title_ar' => 'السودان الجنوبي', 'nationality_en' => 'South Sudanese', 'nationality_ar' => 'سوادني جنوبي'],
            ['code' => 'ES', 'title_en' => 'Spain', 'title_ar' => 'إسبانيا', 'nationality_en' => 'Spanish', 'nationality_ar' => 'إسباني'],
            ['code' => 'SH', 'title_en' => 'Saint Helena', 'title_ar' => 'سانت هيلانة', 'nationality_en' => 'St. Helenian', 'nationality_ar' => 'هيلاني'],
            ['code' => 'SD', 'title_en' => 'Sudan', 'title_ar' => 'السودان', 'nationality_en' => 'Sudanese', 'nationality_ar' => 'سوداني'],
            ['code' => 'SR', 'title_en' => 'Suriname', 'title_ar' => 'سورينام', 'nationality_en' => 'Surinamese', 'nationality_ar' => 'سورينامي'],
            ['code' => 'SJ', 'title_en' => 'Svalbard and Jan Mayen', 'title_ar' => 'سفالبارد ويان ماين', 'nationality_en' => 'Svalbardian/Jan Mayenian', 'nationality_ar' => 'سفالبارد ويان ماين'],
            ['code' => 'SZ', 'title_en' => 'Swaziland', 'title_ar' => 'سوازيلند', 'nationality_en' => 'Swazi', 'nationality_ar' => 'سوازيلندي'],
            ['code' => 'SE', 'title_en' => 'Sweden', 'title_ar' => 'السويد', 'nationality_en' => 'Swedish', 'nationality_ar' => 'سويدي'],
            ['code' => 'CH', 'title_en' => 'Switzerland', 'title_ar' => 'سويسرا', 'nationality_en' => 'Swiss', 'nationality_ar' => 'سويسري'],
            ['code' => 'SY', 'title_en' => 'Syria', 'title_ar' => 'سوريا', 'nationality_en' => 'Syrian', 'nationality_ar' => 'سوري'],
            ['code' => 'TW', 'title_en' => 'Taiwan', 'title_ar' => 'تايوان', 'nationality_en' => 'Taiwanese', 'nationality_ar' => 'تايواني'],
            ['code' => 'TJ', 'title_en' => 'Tajikistan', 'title_ar' => 'طاجيكستان', 'nationality_en' => 'Tajikistani', 'nationality_ar' => 'طاجيكستاني'],
            ['code' => 'TZ', 'title_en' => 'Tanzania', 'title_ar' => 'تنزانيا', 'nationality_en' => 'Tanzanian', 'nationality_ar' => 'تنزانيي'],
            ['code' => 'TH', 'title_en' => 'Thailand', 'title_ar' => 'تايلندا', 'nationality_en' => 'Thai', 'nationality_ar' => 'تايلندي'],
            ['code' => 'TL', 'title_en' => 'Timor-Leste', 'title_ar' => 'تيمور الشرقية', 'nationality_en' => 'Timor-Lestian', 'nationality_ar' => 'تيموري'],
            ['code' => 'TG', 'title_en' => 'Togo', 'title_ar' => 'توغو', 'nationality_en' => 'Togolese', 'nationality_ar' => 'توغي'],
            ['code' => 'TK', 'title_en' => 'Tokelau', 'title_ar' => 'توكيلاو', 'nationality_en' => 'Tokelaian', 'nationality_ar' => 'توكيلاوي'],
            ['code' => 'TO', 'title_en' => 'Tonga', 'title_ar' => 'تونغا', 'nationality_en' => 'Tongan', 'nationality_ar' => 'تونغي'],
            ['code' => 'TT', 'title_en' => 'Trinidad and Tobago', 'title_ar' => 'ترينيداد وتوباغو', 'nationality_en' => 'Trinidadian/Tobagonian', 'nationality_ar' => 'ترينيداد وتوباغو'],
            ['code' => 'TN', 'title_en' => 'Tunisia', 'title_ar' => 'تونس', 'nationality_en' => 'Tunisian', 'nationality_ar' => 'تونسي'],
            ['code' => 'TR', 'title_en' => 'Turkey', 'title_ar' => 'تركيا', 'nationality_en' => 'Turkish', 'nationality_ar' => 'تركي'],
            ['code' => 'TM', 'title_en' => 'Turkmenistan', 'title_ar' => 'تركمانستان', 'nationality_en' => 'Turkmen', 'nationality_ar' => 'تركمانستاني'],
            ['code' => 'TC', 'title_en' => 'Turks and Caicos Islands', 'title_ar' => 'جزر توركس وكايكوس', 'nationality_en' => 'Turks and Caicos Islands', 'nationality_ar' => 'جزر توركس وكايكوس'],
            ['code' => 'TV', 'title_en' => 'Tuvalu', 'title_ar' => 'توفالو', 'nationality_en' => 'Tuvaluan', 'nationality_ar' => 'توفالي'],
            ['code' => 'UG', 'title_en' => 'Uganda', 'title_ar' => 'أوغندا', 'nationality_en' => 'Ugandan', 'nationality_ar' => 'أوغندي'],
            ['code' => 'UA', 'title_en' => 'Ukraine', 'title_ar' => 'أوكرانيا', 'nationality_en' => 'Ukrainian', 'nationality_ar' => 'أوكراني'],
            ['code' => 'AE', 'title_en' => 'United Arab Emirates', 'title_ar' => 'الإمارات العربية المتحدة', 'nationality_en' => 'Emirati', 'nationality_ar' => 'إماراتي'],
            ['code' => 'GB', 'title_en' => 'United Kingdom', 'title_ar' => 'المملكة المتحدة', 'nationality_en' => 'British', 'nationality_ar' => 'بريطاني'],
            ['code' => 'US', 'title_en' => 'United States', 'title_ar' => 'الولايات المتحدة', 'nationality_en' => 'American', 'nationality_ar' => 'أمريكي'],
            ['code' => 'UM', 'title_en' => 'US Minor Outlying Islands', 'title_ar' => 'قائمة الولايات والمناطق الأمريكية', 'nationality_en' => 'US Minor Outlying Islander', 'nationality_ar' => 'أمريكي'],
            ['code' => 'UY', 'title_en' => 'Uruguay', 'title_ar' => 'أورغواي', 'nationality_en' => 'Uruguayan', 'nationality_ar' => 'أورغواي'],
            ['code' => 'UZ', 'title_en' => 'Uzbekistan', 'title_ar' => 'أوزباكستان', 'nationality_en' => 'Uzbek', 'nationality_ar' => 'أوزباكستاني'],
            ['code' => 'VU', 'title_en' => 'Vanuatu', 'title_ar' => 'فانواتو', 'nationality_en' => 'Vanuatuan', 'nationality_ar' => 'فانواتي'],
            ['code' => 'VE', 'title_en' => 'Venezuela', 'title_ar' => 'فنزويلا', 'nationality_en' => 'Venezuelan', 'nationality_ar' => 'فنزويلي'],
            ['code' => 'VN', 'title_en' => 'Vietnam', 'title_ar' => 'فيتنام', 'nationality_en' => 'Vietnamese', 'nationality_ar' => 'فيتنامي'],
            ['code' => 'VI', 'title_en' => 'Virgin Islands (U.S.)', 'title_ar' => 'الجزر العذراء الأمريكي', 'nationality_en' => 'American Virgin Islander', 'nationality_ar' => 'أمريكي'],
            ['code' => 'VA', 'title_en' => 'Vatican City', 'title_ar' => 'فنزويلا', 'nationality_en' => 'Vatican', 'nationality_ar' => 'فاتيكاني'],
            ['code' => 'WF', 'title_en' => 'Wallis and Futuna Islands', 'title_ar' => 'والس وفوتونا', 'nationality_en' => 'Wallisian/Futunan', 'nationality_ar' => 'فوتوني'],
            ['code' => 'EH', 'title_en' => 'Western Sahara', 'title_ar' => 'الصحراء الغربية', 'nationality_en' => 'Sahrawian', 'nationality_ar' => 'صحراوي'],
            ['code' => 'YE', 'title_en' => 'Yemen', 'title_ar' => 'اليمن', 'nationality_en' => 'Yemeni', 'nationality_ar' => 'يمني'],
            ['code' => 'ZM', 'title_en' => 'Zambia', 'title_ar' => 'زامبيا', 'nationality_en' => 'Zambian', 'nationality_ar' => 'زامبياني'],
            ['code' => 'ZW', 'title_en' => 'Zimbabwe', 'title_ar' => 'زمبابوي', 'nationality_en' => 'Zimbabwean', 'nationality_ar' => 'زمبابوي'],
        ]);
    }
}
