<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class NationalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('nationalities')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::table('nationalities')->insert([
            [ 'title_en' => 'Afghan', 'title_ar' => 'أفغانستاني'],
            [ 'title_en' => 'Albanian', 'title_ar' => 'ألباني'],
            [ 'title_en' => 'Aland Islander', 'title_ar' => 'آلاندي'],
            [ 'title_en' => 'Algerian', 'title_ar' => 'جزائري'],
            [ 'title_en' => 'American Samoan', 'title_ar' => 'أمريكي سامواني'],
            [ 'title_en' => 'Andorran', 'title_ar' => 'أندوري'],
            [ 'title_en' => 'Angolan', 'title_ar' => 'أنقولي'],
            [ 'title_en' => 'Anguillan', 'title_ar' => 'أنغويلي'],
            [ 'title_en' => 'Antarctican', 'title_ar' => 'أنتاركتيكي'],
            [ 'title_en' => 'Antiguan', 'title_ar' => 'بربودي'],
            [ 'title_en' => 'Argentinian', 'title_ar' => 'أرجنتيني'],
            [ 'title_en' => 'Armenian', 'title_ar' => 'أرميني'],
            [ 'title_en' => 'Aruban', 'title_ar' => 'أوروبهيني'],
            [ 'title_en' => 'Australian', 'title_ar' => 'أسترالي'],
            [ 'title_en' => 'Austrian', 'title_ar' => 'نمساوي'],
            [ 'title_en' => 'Azerbaijani', 'title_ar' => 'أذربيجاني'],
            [ 'title_en' => 'Bahamian', 'title_ar' => 'باهاميسي'],
            [ 'title_en' => 'Bahraini', 'title_ar' => 'بحريني'],
            [ 'title_en' => 'Bangladeshi', 'title_ar' => 'بنغلاديشي'],
            [ 'title_en' => 'Barbadian', 'title_ar' => 'بربادوسي'],
            [ 'title_en' => 'Belarusian', 'title_ar' => 'روسي'],
            [ 'title_en' => 'Belgian', 'title_ar' => 'بلجيكي'],
            [ 'title_en' => 'Belizean', 'title_ar' => 'بيليزي'],
            [ 'title_en' => 'Beninese', 'title_ar' => 'بنيني'],
            [ 'title_en' => 'Saint Barthelmian', 'title_ar' => 'سان بارتيلمي'],
            [ 'title_en' => 'Bermudan', 'title_ar' => 'برمودي'],
            [ 'title_en' => 'Bhutanese', 'title_ar' => 'بوتاني'],
            [ 'title_en' => 'Bolivian', 'title_ar' => 'بوليفي'],
            [ 'title_en' => 'Bosnian / Herzegovinian', 'title_ar' => 'بوسني/هرسكي'],
            [ 'title_en' => 'Botswanan', 'title_ar' => 'بوتسواني'],
            [ 'title_en' => 'Bouvetian', 'title_ar' => 'بوفيهي'],
            [ 'title_en' => 'Brazilian', 'title_ar' => 'برازيلي'],
            [ 'title_en' => 'British Indian Ocean Territory', 'title_ar' => 'إقليم المحيط الهندي البريطاني'],
            [ 'title_en' => 'Bruneian', 'title_ar' => 'بروني'],
            [ 'title_en' => 'Bulgarian', 'title_ar' => 'بلغاري'],
            [ 'title_en' => 'Burkinabe', 'title_ar' => 'بوركيني'],
            [ 'title_en' => 'Burundian', 'title_ar' => 'بورونيدي'],
            [ 'title_en' => 'Cambodian', 'title_ar' => 'كمبودي'],
            [ 'title_en' => 'Cameroonian', 'title_ar' => 'كاميروني'],
            [ 'title_en' => 'Canadian', 'title_ar' => 'كندي'],
            [ 'title_en' => 'Cape Verdean', 'title_ar' => 'الرأس الأخضر'],
            [ 'title_en' => 'Caymanian', 'title_ar' => 'كايماني'],
            [ 'title_en' => 'Central African', 'title_ar' => 'أفريقي'],
            [ 'title_en' => 'Chadian', 'title_ar' => 'تشادي'],
            [ 'title_en' => 'Chilean', 'title_ar' => 'شيلي'],
            [ 'title_en' => 'Chinese', 'title_ar' => 'صيني'],
            [ 'title_en' => 'Christmas Islander', 'title_ar' => 'جزيرة عيد الميلاد'],
            [ 'title_en' => 'Cocos Islander', 'title_ar' => 'جزر كوكوس'],
            [ 'title_en' => 'Colombian', 'title_ar' => 'كولومبي'],
            [ 'title_en' => 'Comorian', 'title_ar' => 'جزر القمر'],
            [ 'title_en' => 'Congolese', 'title_ar' => 'كونغي'],
            [ 'title_en' => 'Cook Islander', 'title_ar' => 'جزر كوك'],
            [ 'title_en' => 'Costa Rican', 'title_ar' => 'كوستاريكي'],
            [ 'title_en' => 'Croatian', 'title_ar' => 'كوراتي'],
            [ 'title_en' => 'Cuban', 'title_ar' => 'كوبي'],
            [ 'title_en' => 'Cypriot', 'title_ar' => 'قبرصي'],
            [ 'title_en' => 'Curacian', 'title_ar' => 'كوراساوي'],
            [ 'title_en' => 'Czech', 'title_ar' => 'تشيكي'],
            [ 'title_en' => 'Danish', 'title_ar' => 'دنماركي'],
            [ 'title_en' => 'Djiboutian', 'title_ar' => 'جيبوتي'],
            [ 'title_en' => 'Dominican', 'title_ar' => 'دومينيكي'],
            [ 'title_en' => 'Dominican', 'title_ar' => 'دومينيكي'],
            [ 'title_en' => 'Ecuadorian', 'title_ar' => 'إكوادوري'],
            [ 'title_en' => 'Egyptian', 'title_ar' => 'مصري'],
            [ 'title_en' => 'Salvadoran', 'title_ar' => 'سلفادوري'],
            [ 'title_en' => 'Equatorial Guinean', 'title_ar' => 'غيني'],
            [ 'title_en' => 'Eritrean', 'title_ar' => 'إريتيري'],
            [ 'title_en' => 'Estonian', 'title_ar' => 'استوني'],
            [ 'title_en' => 'Ethiopian', 'title_ar' => 'أثيوبي'],
            [ 'title_en' => 'Falkland Islander', 'title_ar' => 'فوكلاندي'],
            [ 'title_en' => 'Faroese', 'title_ar' => 'جزر فارو'],
            [ 'title_en' => 'Fijian', 'title_ar' => 'فيجي'],
            [ 'title_en' => 'Finnish', 'title_ar' => 'فنلندي'],
            [ 'title_en' => 'French', 'title_ar' => 'فرنسي'],
            [ 'title_en' => 'French Guianese', 'title_ar' => 'غويانا الفرنسية'],
            [ 'title_en' => 'French Polynesian', 'title_ar' => 'بولينيزيي'],
            [ 'title_en' => 'French', 'title_ar' => 'أراض فرنسية جنوبية وأنتارتيكية'],
            [ 'title_en' => 'Gabonese', 'title_ar' => 'غابوني'],
            [ 'title_en' => 'Gambian', 'title_ar' => 'غامبي'],
            [ 'title_en' => 'Georgian', 'title_ar' => 'جيورجي'],
            [ 'title_en' => 'German', 'title_ar' => 'ألماني'],
            [ 'title_en' => 'Ghanaian', 'title_ar' => 'غاني'],
            [ 'title_en' => 'Gibraltar', 'title_ar' => 'جبل طارق'],
            [ 'title_en' => 'Guernsian', 'title_ar' => 'غيرنزي'],
            [ 'title_en' => 'Greek', 'title_ar' => 'يوناني'],
            [ 'title_en' => 'Greenlandic', 'title_ar' => 'جرينلاندي'],
            [ 'title_en' => 'Grenadian', 'title_ar' => 'غرينادي'],
            [ 'title_en' => 'Guadeloupe', 'title_ar' => 'جزر جوادلوب'],
            [ 'title_en' => 'Guamanian', 'title_ar' => 'جوامي'],
            [ 'title_en' => 'Guatemalan', 'title_ar' => 'غواتيمالي'],
            [ 'title_en' => 'Guinean', 'title_ar' => 'غيني'],
            [ 'title_en' => 'Guinea-Bissauan', 'title_ar' => 'غيني'],
            [ 'title_en' => 'Guyanese', 'title_ar' => 'غياني'],
            [ 'title_en' => 'Haitian', 'title_ar' => 'هايتي'],
            [ 'title_en' => 'Heard and Mc Donald Islanders', 'title_ar' => 'جزيرة هيرد] وجزر ماكدونالد'],
            [ 'title_en' => 'Honduran', 'title_ar' => 'هندوراسي'],
            [ 'title_en' => 'Hongkongese', 'title_ar' => 'هونغ كونغي'],
            [ 'title_en' => 'Hungarian', 'title_ar' => 'مجري'],
            [ 'title_en' => 'Icelandic', 'title_ar' => 'آيسلندي'],
            [ 'title_en' => 'Indian', 'title_ar' => 'هندي'],
            [ 'title_en' => 'Manx', 'title_ar' => 'ماني'],
            [ 'title_en' => 'Indonesian', 'title_ar' => 'أندونيسيي'],
            [ 'title_en' => 'Iranian', 'title_ar' => 'إيراني'],
            [ 'title_en' => 'Iraqi', 'title_ar' => 'عراقي'],
            [ 'title_en' => 'Irish', 'title_ar' => 'إيرلندي'],
            [ 'title_en' => 'Israeli', 'title_ar' => 'إسرائيلي'],
            [ 'title_en' => 'Italian', 'title_ar' => 'إيطالي'],
            [ 'title_en' => 'Ivory Coastian', 'title_ar' => 'ساحل العاج'],
            [ 'title_en' => 'Jersian', 'title_ar' => 'جيرزي'],
            [ 'title_en' => 'Jamaican', 'title_ar' => 'جمايكي'],
            [ 'title_en' => 'Japanese', 'title_ar' => 'ياباني'],
            [ 'title_en' => 'Jordanian', 'title_ar' => 'أردني'],
            [ 'title_en' => 'Kazakh', 'title_ar' => 'كازاخستاني'],
            [ 'title_en' => 'Kenyan', 'title_ar' => 'كيني'],
            [ 'title_en' => 'I-Kiribati', 'title_ar' => 'كيريباتي'],
            [ 'title_en' => 'North Korean', 'title_ar' => 'كوري'],
            [ 'title_en' => 'South Korean', 'title_ar' => 'كوري'],
            [ 'title_en' => 'Kosovar', 'title_ar' => 'كوسيفي'],
            [ 'title_en' => 'Kuwaiti', 'title_ar' => 'كويتي'],
            [ 'title_en' => 'Kyrgyzstani', 'title_ar' => 'قيرغيزستاني'],
            [ 'title_en' => 'Laotian', 'title_ar' => 'لاوسي'],
            [ 'title_en' => 'Latvian', 'title_ar' => 'لاتيفي'],
            [ 'title_en' => 'Lebanese', 'title_ar' => 'لبناني'],
            [ 'title_en' => 'Basotho', 'title_ar' => 'ليوسيتي'],
            [ 'title_en' => 'Liberian', 'title_ar' => 'ليبيري'],
            [ 'title_en' => 'Libyan', 'title_ar' => 'ليبي'],
            [ 'title_en' => 'Liechtenstein', 'title_ar' => 'ليختنشتيني'],
            [ 'title_en' => 'Lithuanian', 'title_ar' => 'لتوانيي'],
            [ 'title_en' => 'Luxembourger', 'title_ar' => 'لوكسمبورغي'],
            [ 'title_en' => 'Sri Lankian', 'title_ar' => 'سريلانكي'],
            [ 'title_en' => 'Macanese', 'title_ar' => 'ماكاوي'],
            [ 'title_en' => 'Macedonian', 'title_ar' => 'مقدوني'],
            [ 'title_en' => 'Malagasy', 'title_ar' => 'مدغشقري'],
            [ 'title_en' => 'Malawian', 'title_ar' => 'مالاوي'],
            [ 'title_en' => 'Malaysian', 'title_ar' => 'ماليزي'],
            [ 'title_en' => 'Maldivian', 'title_ar' => 'مالديفي'],
            [ 'title_en' => 'Malian', 'title_ar' => 'مالي'],
            [ 'title_en' => 'Maltese', 'title_ar' => 'مالطي'],
            [ 'title_en' => 'Marshallese', 'title_ar' => 'مارشالي'],
            [ 'title_en' => 'Martiniquais', 'title_ar' => 'مارتينيكي'],
            [ 'title_en' => 'Mauritanian', 'title_ar' => 'موريتانيي'],
            [ 'title_en' => 'Mauritian', 'title_ar' => 'موريشيوسي'],
            [ 'title_en' => 'Mahoran', 'title_ar' => 'مايوتي'],
            [ 'title_en' => 'Mexican', 'title_ar' => 'مكسيكي'],
            [ 'title_en' => 'Micronesian', 'title_ar' => 'مايكرونيزيي'],
            [ 'title_en' => 'Moldovan', 'title_ar' => 'مولديفي'],
            [ 'title_en' => 'Monacan', 'title_ar' => 'مونيكي'],
            [ 'title_en' => 'Mongolian', 'title_ar' => 'منغولي'],
            [ 'title_en' => 'Montenegrin', 'title_ar' => 'الجبل الأسود'],
            [ 'title_en' => 'Montserratian', 'title_ar' => 'مونتسيراتي'],
            [ 'title_en' => 'Moroccan', 'title_ar' => 'مغربي'],
            [ 'title_en' => 'Mozambican', 'title_ar' => 'موزمبيقي'],
            [ 'title_en' => 'Myanmarian', 'title_ar' => 'ميانماري'],
            [ 'title_en' => 'Namibian', 'title_ar' => 'ناميبي'],
            [ 'title_en' => 'Nauruan', 'title_ar' => 'نوري'],
            [ 'title_en' => 'Nepalese', 'title_ar' => 'نيبالي'],
            [ 'title_en' => 'Dutch', 'title_ar' => 'هولندي'],
            [ 'title_en' => 'Dutch Antilier', 'title_ar' => 'هولندي'],
            [ 'title_en' => 'New Caledonian', 'title_ar' => 'كاليدوني'],
            [ 'title_en' => 'New Zealander', 'title_ar' => 'نيوزيلندي'],
            [ 'title_en' => 'Nicaraguan', 'title_ar' => 'نيكاراجوي'],
            [ 'title_en' => 'Nigerien', 'title_ar' => 'نيجيري'],
            [ 'title_en' => 'Nigerian', 'title_ar' => 'نيجيري'],
            [ 'title_en' => 'Niuean', 'title_ar' => 'ني'],
            [ 'title_en' => 'Norfolk Islander', 'title_ar' => 'نورفوليكي'],
            [ 'title_en' => 'Northern Marianan', 'title_ar' => 'ماريني'],
            [ 'title_en' => 'Norwegian', 'title_ar' => 'نرويجي'],
            [ 'title_en' => 'Omani', 'title_ar' => 'عماني'],
            [ 'title_en' => 'Pakistani', 'title_ar' => 'باكستاني'],
            [ 'title_en' => 'Palauan', 'title_ar' => 'بالاوي'],
            [ 'title_en' => 'Palestinian', 'title_ar' => 'فلسطيني'],
            [ 'title_en' => 'Panamanian', 'title_ar' => 'بنمي'],
            [ 'title_en' => 'Papua New Guinean', 'title_ar' => 'بابوي'],
            [ 'title_en' => 'Paraguayan', 'title_ar' => 'بارغاوي'],
            [ 'title_en' => 'Peruvian', 'title_ar' => 'بيري'],
            [ 'title_en' => 'Filipino', 'title_ar' => 'فلبيني'],
            [ 'title_en' => 'Pitcairn Islander', 'title_ar' => 'بيتكيرني'],
            [ 'title_en' => 'Polish', 'title_ar' => 'بوليني'],
            [ 'title_en' => 'Portuguese', 'title_ar' => 'برتغالي'],
            [ 'title_en' => 'Puerto Rican', 'title_ar' => 'بورتي'],
            [ 'title_en' => 'Qatari', 'title_ar' => 'قطري'],
            [ 'title_en' => 'Reunionese', 'title_ar' => 'ريونيوني'],
            [ 'title_en' => 'Romanian', 'title_ar' => 'روماني'],
            [ 'title_en' => 'Russian', 'title_ar' => 'روسي'],
            [ 'title_en' => 'Rwandan', 'title_ar' => 'رواندا'],
            [ 'title_en' => 'Kittitian/Nevisian', 'title_ar' => 'سانت كيتس ونيفس'],
            [ 'title_en' => 'St. Martian(French)', 'title_ar' => 'ساينت مارتني فرنسي'],
            [ 'title_en' => 'St. Martian(Dutch)', 'title_ar' => 'ساينت مارتني هولندي'],
            [ 'title_en' => 'St. Pierre and Miquelon', 'title_ar' => 'سان بيير وميكلوني'],
            [ 'title_en' => 'Saint Vincent and the Grenadines', 'title_ar' => 'سانت فنسنت وجزر غرينادين'],
            [ 'title_en' => 'Samoan', 'title_ar' => 'ساموي'],
            [ 'title_en' => 'Sammarinese', 'title_ar' => 'ماريني'],
            [ 'title_en' => 'Sao Tomean', 'title_ar' => 'ساو تومي وبرينسيبي'],
            [ 'title_en' => 'Saudi Arabian', 'title_ar' => 'سعودي'],
            [ 'title_en' => 'Senegalese', 'title_ar' => 'سنغالي'],
            [ 'title_en' => 'Serbian', 'title_ar' => 'صربي'],
            [ 'title_en' => 'Seychellois', 'title_ar' => 'سيشيلي'],
            [ 'title_en' => 'Sierra Leonean', 'title_ar' => 'سيراليوني'],
            [ 'title_en' => 'Singaporean', 'title_ar' => 'سنغافوري'],
            [ 'title_en' => 'Slovak', 'title_ar' => 'سولفاكي'],
            [ 'title_en' => 'Slovenian', 'title_ar' => 'سولفيني'],
            [ 'title_en' => 'Solomon Island', 'title_ar' => 'جزر سليمان'],
            [ 'title_en' => 'Somali', 'title_ar' => 'صومالي'],
            [ 'title_en' => 'South African', 'title_ar' => 'أفريقي'],
            [ 'title_en' => 'South Georgia and the South Sandwich', 'title_ar' => 'لمنطقة القطبية الجنوبية'],
            [ 'title_en' => 'South Sudanese', 'title_ar' => 'سوادني جنوبي'],
            [ 'title_en' => 'Spanish', 'title_ar' => 'إسباني'],
            [ 'title_en' => 'St. Helenian', 'title_ar' => 'هيلاني'],
            [ 'title_en' => 'Sudanese', 'title_ar' => 'سوداني'],
            [ 'title_en' => 'Surinamese', 'title_ar' => 'سورينامي'],
            [ 'title_en' => 'Svalbardian/Jan Mayenian', 'title_ar' => 'سفالبارد ويان ماين'],
            [ 'title_en' => 'Swazi', 'title_ar' => 'سوازيلندي'],
            [ 'title_en' => 'Swedish', 'title_ar' => 'سويدي'],
            [ 'title_en' => 'Swiss', 'title_ar' => 'سويسري'],
            [ 'title_en' => 'Syrian', 'title_ar' => 'سوري'],
            [ 'title_en' => 'Taiwanese', 'title_ar' => 'تايواني'],
            [ 'title_en' => 'Tajikistani', 'title_ar' => 'طاجيكستاني'],
            [ 'title_en' => 'Tanzanian', 'title_ar' => 'تنزانيي'],
            [ 'title_en' => 'Thai', 'title_ar' => 'تايلندي'],
            [ 'title_en' => 'Timor-Lestian', 'title_ar' => 'تيموري'],
            [ 'title_en' => 'Togolese', 'title_ar' => 'توغي'],
            [ 'title_en' => 'Tokelaian', 'title_ar' => 'توكيلاوي'],
            [ 'title_en' => 'Tongan', 'title_ar' => 'تونغي'],
            [ 'title_en' => 'Trinidadian/Tobagonian', 'title_ar' => 'ترينيداد وتوباغو'],
            [ 'title_en' => 'Tunisian', 'title_ar' => 'تونسي'],
            [ 'title_en' => 'Turkish', 'title_ar' => 'تركي'],
            [ 'title_en' => 'Turkmen', 'title_ar' => 'تركمانستاني'],
            [ 'title_en' => 'Turks and Caicos Islands', 'title_ar' => 'جزر توركس وكايكوس'],
            [ 'title_en' => 'Tuvaluan', 'title_ar' => 'توفالي'],
            [ 'title_en' => 'Ugandan', 'title_ar' => 'أوغندي'],
            [ 'title_en' => 'Ukrainian', 'title_ar' => 'أوكراني'],
            [ 'title_en' => 'Emirati', 'title_ar' => 'إماراتي'],
            [ 'title_en' => 'British', 'title_ar' => 'بريطاني'],
            [ 'title_en' => 'American', 'title_ar' => 'أمريكي'],
            [ 'title_en' => 'US Minor Outlying Islander', 'title_ar' => 'أمريكي'],
            [ 'title_en' => 'Uruguayan', 'title_ar' => 'أورغواي'],
            [ 'title_en' => 'Uzbek', 'title_ar' => 'أوزباكستاني'],
            [ 'title_en' => 'Vanuatuan', 'title_ar' => 'فانواتي'],
            [ 'title_en' => 'Venezuelan', 'title_ar' => 'فنزويلي'],
            [ 'title_en' => 'Vietnamese', 'title_ar' => 'فيتنامي'],
            [ 'title_en' => 'American Virgin Islander', 'title_ar' => 'أمريكي'],
            [ 'title_en' => 'Vatican', 'title_ar' => 'فاتيكاني'],
            [ 'title_en' => 'Wallisian/Futunan', 'title_ar' => 'فوتوني'],
            [ 'title_en' => 'Sahrawian', 'title_ar' => 'صحراوي'],
            [ 'title_en' => 'Yemeni', 'title_ar' => 'يمني'],
            [ 'title_en' => 'Zambian', 'title_ar' => 'زامبياني'],
            [ 'title_en' => 'Zimbabwean', 'title_ar' => 'زمبابوي'],
        ]);
    }
}
